"""Pytest configuration and shared fixtures.

This module provides shared fixtures for all test modules.
Fixtures include sample data, mock objects, and test utilities.
"""

import json
import pytest
from pathlib import Path
from typing import Dict
from unittest.mock import Mock, AsyncMock

from src.common.config import Config
from src.workflow.orchestrator import Orchestrator


@pytest.fixture
def sample_health_report() -> Dict:
    """Load sample health report from resources.

    Returns:
        Dict containing health report data
    """
    sample_path = Config.DATA_DIR / "sample_health_report.json"
    with sample_path.open("r", encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
def sample_user_profile() -> Dict:
    """Create sample user profile for testing.

    Returns:
        Dict containing user profile data
    """
    return {
        "age": 45,
        "gender": "male",
        "height_cm": 175,
        "weight_kg": 85,
        "occupation": "office_worker",
        "work_schedule": {
            "typical_work_hours": "9-6",
            "work_days_per_week": 5,
            "commute_time_minutes": 30
        },
        "lifestyle": {
            "activity_level": "sedentary",
            "exercise_frequency": "1-2 times per week",
            "sleep_hours": 6,
            "stress_level": "moderate"
        },
        "dietary_preferences": {
            "diet_type": "no_restrictions",
            "allergies": [],
            "dislikes": ["liver", "oysters"],
            "preferred_cuisines": ["asian", "mediterranean"]
        },
        "fitness_profile": {
            "current_fitness_level": "beginner",
            "fitness_goals": ["lose_weight", "improve_cardiovascular_health"],
            "exercise_limitations": ["knee_pain"],
            "preferred_activities": ["walking", "swimming"]
        },
        "social_support": {
            "family_support": "high",
            "availability_for_lifestyle_changes": "moderate"
        }
    }


@pytest.fixture
def mock_llm_response_analyst() -> Dict:
    """Mock ADK LLM response for ReportAnalyst.

    Returns:
        Dict containing mocked health analysis
    """
    return {
        "health_metrics": {
            "cholesterol": {
                "total": 220,
                "ldl": 150,
                "hdl": 40,
                "triglycerides": 180
            },
            "blood_pressure": {
                "systolic": 140,
                "diastolic": 90
            },
            "glucose": {
                "fasting": 110
            },
            "bmi": 28.5
        },
        "risk_tags": [
            "high_cholesterol",
            "elevated_blood_pressure",
            "overweight",
            "prediabetes_risk"
        ]
    }


@pytest.fixture
def mock_llm_response_planner() -> str:
    """Mock ADK LLM response for LifestylePlanner.

    Returns:
        String containing mocked lifestyle plan
    """
    return """# Personalized Health Improvement Plan

## Executive Summary
Based on your health metrics, we've identified key areas for improvement: cholesterol management, blood pressure control, weight management, and cardiovascular health.

## Dietary Recommendations
1. **Reduce saturated fat intake** to lower LDL cholesterol
2. **Increase fiber** through whole grains and vegetables
3. **Limit sodium** to help manage blood pressure

## Exercise Plan
1. **Walking**: 30 minutes daily, 5 days per week
2. **Swimming**: 2 sessions per week (knee-friendly)
3. Gradual progression to avoid knee strain

## Lifestyle Modifications
1. **Sleep**: Aim for 7-8 hours nightly
2. **Stress management**: Daily 10-minute meditation
3. **Hydration**: 8 glasses of water per day

## Monitoring
- Weekly blood pressure checks
- Monthly weight tracking
- Follow-up lab work in 3 months

*Disclaimer: This plan is generated by AI and should be reviewed with your healthcare provider before implementation.*
"""


@pytest.fixture
def mock_llm_response_guard_approve() -> Dict:
    """Mock ADK LLM response for SafetyGuard (APPROVE).

    Returns:
        Dict containing mocked approval validation result
    """
    return {
        "decision": "APPROVE",
        "feedback": "Plan meets all safety criteria. Recommendations are appropriate for the user's health status and limitations.",
        "violations": [],
        "safety_score": 95
    }


@pytest.fixture
def mock_llm_response_guard_reject() -> Dict:
    """Mock ADK LLM response for SafetyGuard (REJECT).

    Returns:
        Dict containing mocked rejection validation result
    """
    return {
        "decision": "REJECT",
        "feedback": "Plan contains unsafe recommendations. Please revise.",
        "violations": [
            {
                "code": "UNSAFE_EXERCISE",
                "severity": "HIGH",
                "description": "Recommended running despite knee_pain limitation"
            }
        ],
        "safety_score": 45
    }


@pytest.fixture
def orchestrator_instance() -> Orchestrator:
    """Create Orchestrator instance for testing.

    Returns:
        Orchestrator instance with default model
    """
    return Orchestrator(model_name="gemini-pro")


@pytest.fixture
def mock_adk_workflow_run():
    """Mock ADK workflow.run() method.

    Returns:
        AsyncMock that can be used to mock workflow.run()
    """
    mock = AsyncMock()
    mock.return_value = {
        "health_analysis": {
            "health_metrics": {"cholesterol_total": 220},
            "risk_tags": ["high_cholesterol"]
        },
        "current_plan": "# Mock Plan\nThis is a test plan.",
        "validation_result": {
            "decision": "APPROVE",
            "feedback": "Plan approved"
        }
    }
    return mock


@pytest.fixture
def temp_output_dir(tmp_path):
    """Create temporary output directory for testing.

    Args:
        tmp_path: pytest built-in fixture for temporary directories

    Returns:
        Path to temporary output directory
    """
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    return output_dir
