import streamlit as st
import requests
import json
import markdown
from xhtml2pdf import pisa
from io import BytesIO
import time

# --- Configuration ---
API_URL = "http://localhost:8000/api/v1"
PAGE_TITLE = "Health Action Squad"
PAGE_ICON = "🩺"

# --- Page Setup ---
st.set_page_config(
    page_title=PAGE_TITLE,
    page_icon=PAGE_ICON,
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- Custom CSS ---
st.markdown(
    """
    <style>
    /* Global Font Size Increase */
    html {
        font-size: 18px;
    }
    
    .main {
        background-color: #f8f9fa;
    }
    
    /* Buttons */
    .stButton>button {
        width: 100%;
        border-radius: 8px;
        height: 3.5em;
        font-size: 1.1rem !important;
        font-weight: bold;
    }
    .stButton>button:hover {
        border-color: #4285F4;
        color: #4285F4;
    }
    
    /* Report Container */
    .report-container {
        background-color: white;
        padding: 2.5rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        margin-top: 1rem;
    }
    
    /* Metric Card */
    .metric-card {
        background-color: #ffffff;
        padding: 1.2rem;
        border-radius: 8px;
        border-left: 5px solid #4285F4;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    
    /* Headers */
    h1 {
        color: #2c3e50;
        font-size: 2.5rem !important;
    }
    h2 {
        color: #2c3e50;
        font-size: 2rem !important;
    }
    h3 {
        color: #2c3e50;
        font-size: 1.5rem !important;
    }
    
    /* Text Content */
    .stMarkdown p, .stMarkdown li, .stText {
        font-size: 1.1rem !important;
        line-height: 1.6 !important;
    }
    
    /* Input Labels */
    .stTextInput label, .stNumberInput label, .stSelectbox label, .stMultiSelect label, .stFileUploader label {
        font-size: 1.1rem !important;
    }
    
    .highlight {
        color: #4285F4;
        font-weight: bold;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# --- Session State Initialization ---
if "parsed_data" not in st.session_state:
    st.session_state.parsed_data = None
if "current_plan" not in st.session_state:
    st.session_state.current_plan = None
if "risk_tags" not in st.session_state:
    st.session_state.risk_tags = []

# --- Helper Functions ---
def convert_markdown_to_pdf(markdown_content):
    """Convert Markdown to PDF bytes."""
    html_content = markdown.markdown(markdown_content)
    
    # Add some basic styling for the PDF
    styled_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 12pt; line-height: 1.5; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #4285F4; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 20px; }}
            strong {{ color: #2c3e50; }}
            ul {{ margin-bottom: 15px; }}
        </style>
    </head>
    <body>
        {html_content}
        <br><br>
        <hr>
        <p style="font-size: 10pt; color: #7f8c8d; text-align: center;">
            Generated by Health Action Squad AI. Not medical advice. Consult a doctor.
        </p>
    </body>
    </html>
    """
    
    pdf_file = BytesIO()
    pisa_status = pisa.CreatePDF(styled_html, dest=pdf_file)
    
    if pisa_status.err:
        return None
    return pdf_file.getvalue()

def call_upload_api(files, profile_data):
    """Call the upload_report API."""
    files_payload = [
        ("files", (file.name, file.getvalue(), file.type)) for file in files
    ]
    
    # Convert lists/dicts to JSON strings for the API
    data_payload = {
        "age": profile_data["age"],
        "gender": profile_data["gender"],
        "health_goal": profile_data["health_goal"],
        "dietary_restrictions": json.dumps(profile_data["dietary_restrictions"]),
        "exercise_barriers": json.dumps(profile_data["exercise_barriers"]),
    }
    
    try:
        response = requests.post(
            f"{API_URL}/upload_report",
            files=files_payload,
            data=data_payload,
            timeout=120 # Long timeout for OCR + Agents
        )
        return response
    except requests.exceptions.RequestException as e:
        st.error(f"Connection Error: {e}")
        return None

def call_upload_api_stream(files, profile_data):
    """Call the upload_report_stream API and yield progress events."""
    files_payload = [
        ("files", (file.name, file.getvalue(), file.type)) for file in files
    ]
    
    data_payload = {
        "age": profile_data["age"],
        "gender": profile_data["gender"],
        "health_goal": profile_data["health_goal"],
        "dietary_restrictions": json.dumps(profile_data["dietary_restrictions"]),
        "exercise_barriers": json.dumps(profile_data["exercise_barriers"]),
    }
    
    try:
        with requests.post(
            f"{API_URL}/upload_report_stream",
            files=files_payload,
            data=data_payload,
            stream=True,
            timeout=120
        ) as response:
            if response.status_code != 200:
                try:
                    detail = response.json().get('detail', 'Unknown error')
                except:
                    detail = f"Status {response.status_code}"
                yield {"type": "error", "message": detail}
                return

            current_event = None
            for line in response.iter_lines():
                if not line: continue
                decoded_line = line.decode('utf-8')
                
                if decoded_line.startswith("event:"):
                    current_event = decoded_line[6:].strip()
                elif decoded_line.startswith("data:"):
                    data_content = decoded_line[5:].strip()
                    if current_event == "progress":
                        yield {"type": "progress", "message": data_content}
                    elif current_event == "result":
                        yield {"type": "result", "payload": json.loads(data_content)}
                    elif current_event == "error":
                        yield {"type": "error", "payload": json.loads(data_content)}
                        
    except requests.exceptions.RequestException as e:
        yield {"type": "error", "message": f"Connection Error: {e}"}

def call_generate_api(parsed_data, profile_data):
    """Call the generate_plan API (Regenerate)."""
    payload = {
        "health_report": parsed_data,
        "user_profile": profile_data
    }
    
    try:
        response = requests.post(
            f"{API_URL}/generate_plan",
            json=payload,
            timeout=60
        )
        return response
    except requests.exceptions.RequestException as e:
        st.error(f"Connection Error: {e}")
        return None

# --- Sidebar: User Profile ---
with st.sidebar:
    st.image("docs/images/health_report_anxiety_banner.png", width='stretch')
    st.title("👤 User Profile")
    st.markdown("---")
    
    age = st.number_input("Age", min_value=18, max_value=120, value=35)
    gender = st.selectbox("Gender", ["male", "female", "other"])
    
    st.markdown("### 🎯 Goals & Preferences")
    health_goal = st.text_input("Primary Health Goal", "Reduce cholesterol and improve energy")
    
    dietary_restrictions = st.multiselect(
        "Dietary Restrictions",
        ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Nut-Free", "Low-Carb", "Halal", "Kosher"],
        default=[]
    )
    
    exercise_barriers = st.multiselect(
        "Exercise Barriers",
        ["Limited Time", "Joint Pain", "No Gym Access", "Fatigue", "Lack of Motivation"],
        default=[]
    )
    
    profile_data = {
        "age": age,
        "gender": gender,
        "health_goal": health_goal,
        "dietary_restrictions": dietary_restrictions,
        "exercise_barriers": exercise_barriers
    }
    
    st.markdown("---")
    st.info("💡 **Tip**: Adjust your profile and click 'Regenerate Plan' to get different advice!")

# --- Main Content ---
st.title("🩺 Health Action Squad")
st.markdown(
    """
    ### Your Personal AI Health Concierge
    Upload your health check report (images or PDF) to get a personalized, actionable plan.
    """
)

# --- Upload Section ---
uploaded_files = st.file_uploader(
    "📄 Upload Health Report (Max 4 files)", 
    type=["pdf", "jpg", "jpeg", "png"], 
    accept_multiple_files=True
)

if uploaded_files:
    if len(uploaded_files) > 4:
        st.warning("⚠️ Please upload a maximum of 4 files.")
    else:
        col1, col2 = st.columns([1, 2])
        
        with col1:
            if st.button("🚀 Analyze Report", type="primary"):
                # Create a placeholder for progress updates
                status_container = st.status("🕵️‍♂️ Starting analysis...", expanded=True)
                
                # Stream updates
                final_result = None
                error_message = None
                
                for update in call_upload_api_stream(uploaded_files, profile_data):
                    if update["type"] == "progress":
                        status_container.write(f"👉 {update['message']}")
                        status_container.update(label=f"🕵️‍♂️ {update['message']}")
                    elif update["type"] == "result":
                        final_result = update["payload"]
                        status_container.update(label="✅ Analysis Complete!", state="complete", expanded=False)
                    elif update["type"] == "error":
                        if "message" in update:
                            error_message = update["message"]
                        else:
                            error_message = update["payload"].get("detail", "Unknown error")
                        status_container.update(label="❌ Analysis Failed", state="error")
                
                if final_result:
                    st.session_state.parsed_data = final_result.get("parsed_data", {})
                    st.session_state.current_plan = final_result.get("plan", "")
                    st.session_state.risk_tags = final_result.get("risk_tags", [])
                    st.success("Analysis Complete!")
                    st.rerun() # Rerun to show results
                elif error_message:
                    st.error(f"Error: {error_message}")

        with col2:
            if st.session_state.parsed_data:
                if st.button("🔄 Regenerate Plan"):
                    with st.spinner("🧠 Rethinking plan based on new profile..."):
                        response = call_generate_api(st.session_state.parsed_data, profile_data)
                        
                        if response and response.status_code == 200:
                            result = response.json()
                            st.session_state.current_plan = result.get("plan", "")
                            st.session_state.risk_tags = result.get("risk_tags", [])
                            st.success("Plan Regenerated!")
                        elif response:
                            st.error(f"Error: {response.json().get('detail', 'Unknown error')}")

# --- Results Section ---
if st.session_state.current_plan:
    st.markdown("---")
    
    # Risk Tags
    if st.session_state.risk_tags:
        st.markdown("### 🚨 Identified Risks")
        tags_html = " ".join([f'<span style="background-color: #ffebee; color: #c62828; padding: 4px 8px; border-radius: 16px; font-size: 0.9em; margin-right: 5px;">{tag}</span>' for tag in st.session_state.risk_tags])
        st.markdown(tags_html, unsafe_allow_html=True)
    
    # The Plan
    st.markdown("### 📋 Your Action Plan")
    
    with st.container():
        st.markdown('<div class="report-container">', unsafe_allow_html=True)
        st.markdown(st.session_state.current_plan)
        st.markdown('</div>', unsafe_allow_html=True)
    
    # Download Button
    st.markdown("### 📥 Download")
    pdf_bytes = convert_markdown_to_pdf(st.session_state.current_plan)
    
    if pdf_bytes:
        st.download_button(
            label="📄 Download Plan as PDF",
            data=pdf_bytes,
            file_name="health_action_plan.pdf",
            mime="application/pdf",
        )
    else:
        st.error("Failed to generate PDF.")

# --- Footer ---
st.markdown("---")
st.markdown(
    """
    <div style="text-align: center; color: #7f8c8d; font-size: 0.8em;">
        Health Action Squad © 2025 | 
        <a href="https://github.com/KLTsai/health-action-squad">GitHub</a>
    </div>
    """,
    unsafe_allow_html=True
)
